custom_categories:
    - name: Sessions
      children:
          - Session
          - SessionError
          - SessionHTTPErrorDomain
          - SessionProtocol

    - name: Messages
      children:
          - Message
          - MessageProtocol

    - name: URLSession
      children:
          - UploadRequest
          - URLSession
