custom_categories:
    - name: Sessions
      children:
          - Session
          - SessionError
          - SessionType
    
    - name: Messages
      children:
          - Message
          - MessageType
    
    - name: NSURLSession
      children:
          - NSURLSession
          - UploadRequest
          - UploadRequestSource
          - Error
          - Request
          - Value
          
excluded_files:
    # jazzy includes extensions of internal types as a documentation root
    - Shirley/TransformSession.swift
