custom_categories:
    - name: Sessions
      children:
          - Session
          - SessionError
          - SessionType
    
    - name: Messages
      children:
          - Message
          - MessageType
    
    - name: NSURLSession
      children:
          - NSURLSession
          - Error
          - Request
          - Value