custom_categories:
    - name: Sessions
      children:
          - Session
          - SessionError
          - SessionType
          - SessionTypeHTTPErrorDomain
    
    - name: Messages
      children:
          - Message
          - MessageType
    
    - name: NSURLSession
      children:
          - NSURLSession
          - UploadRequest
          - UploadRequestSource
