language: objective-c
xcode_project: Shirley.xcodeproj
xcode_scheme: Shirley-OSX
osx_image: xcode7.1
before_install: true
install: true
git:
  submodules: false
script:
  - curl -OlL "https://github.com/Carthage/Carthage/releases/download/0.9.4/Carthage.pkg"
  - sudo installer -pkg "Carthage.pkg" -target /
  - rm "Carthage.pkg"
  - /usr/local/bin/carthage bootstrap --platform Mac
  - xctool -project Shirley.xcodeproj -scheme Shirley-OSX
  - xcodebuild test -project Shirley.xcodeproj -scheme Shirley-OSX