language: objective-c
xcode_project: Shirley.xcodeproj
xcode_scheme: Shirley-OSX
osx_image: xcode8
before_install: true
install: true
git:
  submodules: false
script:
  - /usr/local/bin/carthage bootstrap --platform Mac --no-use-binaries
  - xcodebuild -project Shirley.xcodeproj -scheme Shirley-OSX
  - xcodebuild test -project Shirley.xcodeproj -scheme Shirley-OSX
